### ISSUE TITLE
mac OS X Lion - unable to load shared library

### ISSUE THREAD

**Issue by homeyer** [mariano/node-db-oracle#19]
Successfully installed db-oracle using node 0.6.5, after:

```
ln -s libclntsh.dylib.10.1 libclntsh.dylib
ln -s libocci.dylib.10.1 libocci.dylib
ln -s libnnz10.dylib libnnz11.dylib
```

In `app.js` I have one line:

```
var oracle = require('db-oracle');
```

When I run `node app.js` from `/code/oracle_node`, I get:

```
node.js:201
    throw e; // process.nextTick error, or 'error' event on first tick
          ^
Error: Unable to load shared library /code/oracle_node/node_modules/db-oracle/build/Release/oracle_bindings.node
at Object..node (module.js:463:11)
at Module.load (module.js:351:31)
at Function._load (module.js:310:12)
at Module.require (module.js:357:17)
at require (module.js:368:17)
at Object.<anonymous> (/code/oracle_node/node_modules/db-oracle/db-oracle.js:18:15)
at Module._compile (module.js:432:26)
at Object..js (module.js:450:10)
at Module.load (module.js:351:31)
at Function._load (module.js:310:12)
```

Any ideas?

**Comment by sergioramos** [comment]
+1, on Snow Leopard

On db.oracle.js there is this code:
    `try {
        binding = require("./build/default/oracle_bindings");
    } catch(error) {
        binding = require("./build/Release/oracle_bindings");
    }`

Witch i edited to this:
    `try {
        binding = require("./build/default/oracle_bindings");
    } catch(error) {
        console.log(error);
    }`

And got this errors:
**node 0.4.12**
    `{
        stack: [Getter/Setter],
      arguments: undefined,
      type: undefined,
      message: 'dlopen(/Users/ramitos/node_modules/db-oracle/build/default/oracle_bindings.node, 1): Symbol not found: __ZTIN6oracle4occi12SQLExceptionE\n  Referenced from: /Users/ramitos/node_modules/db-oracle/build/default/oracle_bindings.node\n  Expected in: flat namespace\n in /Users/ramitos/node_modules/db-oracle/build/default/oracle_bindings.node'
    }`

**0.5.10**
    `[
        Error: dlopen(/Users/ramitos/node_modules/db-oracle/build/default/oracle_bindings.node, 1):
        Symbol not found: __ZTIN6oracle4occi12SQLExceptionE
        Referenced from: /Users/ramitos/node_modules/db-oracle/build/default/oracle_bindings.node
        Expected in: flat namespace in /Users/ramitos/node_modules/db-oracle/build/default/oracle_bindings.node
    ]`

**0.6.3**
    `[
        Error: Unable to load shared library /Users/ramitos/node_modules/db-oracle/build/default/oracle_bindings.node
    ]`
**0.6.4**
    `[
        Error: Unable to load shared library /Users/ramitos/node_modules/db-oracle/build/default/oracle_bindings.node
    ]`
**0.6.5**
    `[
        Error: Unable to load shared library /Users/ramitos/node_modules/db-oracle/build/default/oracle_bindings.node
    ]`

**Comment by tritowntim** [comment]
I am seeing this as well on Mac Lion with 0.6.6.  The issue seems similar to this...  https://github.com/Sannis/node-mysql-libmysqlclient/issues/107

**Comment by rbriank** [comment]
+1 on Snow Leopard.

Anyone solve this?

**Comment by homeyer** [comment]
You might have better luck with this: https://github.com/nearinfinity/node-oracle

**Comment by rbriank** [comment]
I tried that and am getting the exact same problem. I'm guessing there is
something wrong with it on the Mac.

I do have navicat running so it's _possible_, just not sure how to do it.

Thanks!!

On Tuesday, March 13, 2012, Andrew Homeyer <
reply@reply.github.com>
wrote:

**Comment by rbriank** [comment]
I added in a tnsname.ora file and it's gotten past the instantiation step, but now it just hangs once it tries to make a connection - no events are delivered.  It also doesn't seem to matter what hostname I use.  Very weird.

**Comment by roymax** [comment]
+1 on Lion 7.3

**Comment by Sannis** [comment]
Solution: https://github.com/Sannis/node-mysql-libmysqlclient/issues/107#issuecomment-3260917
