### ISSUE TITLE
Segfaulting db-oracle

### ISSUE THREAD

**Issue by aprice2704** [mariano/node-db-oracle#29]
Hi there!

I'm compiling db-oracle against 11_2 oracle on linux mint with node 0.7.7-exp. Compiles ok via npm etc. but segfaults as soon as I run the sample program. No error.

I tried the tests.js and oracle-test.js files with the same result. oracle-test-async.js gave a slightly different problem:

node oracle-test-async.js

node.js:216
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: Cannot find module '/home/aprice/node_modules/db-oracle/build/oracle-test-async.js'
    at Function._resolveFilename (module.js:334:15)
    at Function._load (module.js:281:25)
    at Array.0 (module.js:483:10)
    at EventEmitter._tickCallback (node.js:207:41)

I really dunno what's happening here -- help much appreciated! Also been work with Joe trying to use his driver, so maybe I am just cursed/stupid :(

Andy

**Comment by arhi37** [comment]
node test.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'db-oracle'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/root/test.js:1:76)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)

I'm stupid to :(
