### ISSUE TITLE
Error running on node 0.10 --  undefined symbol:  ev_default_loop_ptr

### ISSUE THREAD

**Issue by jlubean** [mariano/node-db-oracle#50]
I get the following error when I try to use db-oracle on node 0.10 (but don't get the error on node 0.8.22):

module.js:356
  Module._extensions&#91;extension&#93;(this, filename);
                               ^
Error: .../node_modules/db-oracle/build/Release/oracle_bindings.node: undefined symbol: ev_default_loop_ptr
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (.../node_modules/db-oracle/db-oracle.js:18:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by JohnMcLear** [comment]
+1

**Comment by buffalobillion** [comment]
Any news on this one? We'd love to use this with node 0.10

**Comment by gtournie** [comment]
same error on db-mysql...

**Comment by asmuelle** [comment]
And same problem with node-expat

**Comment by zorrofox** [comment]
I just rebuild the on 0.10 to resolve this issue.

**Comment by SyntaxRules** [comment]
Rolling back to node v0.8.23 was the only way I could avoid this error.
Here are some other symbols that need to be updated

```
ev_ref is deprecated, use uv_ref
ev_unref is deprecated, use uv_unref
```
