### ISSUE TITLE
Symbol not found: _ev_default_loop_ptr

### ISSUE THREAD

**Issue by SyntaxRules** [mariano/node-db-oracle#54]
I get an error when trying to run a node.js application with db-oracle.

``` module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: dlopen(/Users/XX/Documents/Projects/XX/node_modules/db-oracle/build/Release/oracle_bindings.node, 1): Symbol not found: _ev_default_loop_ptr
  Referenced from: /Users/XX/Documents/Projects/XX/node_modules/db-oracle/build/Release/oracle_bindings.node
  Expected in: flat namespace
 in /Users/XX/Documents/Projects/XX/node_modules/db-oracle/build/Release/oracle_bindings.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/XX/Documents/Projects/XX/node_modules/db-oracle/db-oracle.js:20:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Process finished with exit code 8
```

I double checked all of my environment variables and installation. I'm on Mac OSX.
Thanks for any help

**Comment by SyntaxRules** [comment]
Closed as stale.
