### ISSUE TITLE
db-oracle Mac OS X installation - Part II

### ISSUE THREAD

**Issue by josecardozo** [mariano/node-db-oracle#9]
Hello again, 

I'm trying to install the db-oracle on a Mac OS X Lion machine, and everything goes fine in the installation but, everytime that I try to run my application an error occurs. Just like that:

```
node server_js.js
node.js:189
    throw e; // process.nextTick error, or 'error' event on first tick
    ^
Error: dlopen(/Users/ricky/node_modules/db-oracle/build/default/oracle_bindings.node, 1): Symbol not found:  ZTIN6oracle4occi12SQLExceptionE
Referenced from: /Users/ricky/node_modules/db-oracle/build/default/oracle_bindings.node
Expected in: flat namespace
in /Users/ricky/node_modules/db-oracle/build/default/oracle_bindings.node
at Object..node (module.js:451:11)
at Module.load (module.js:334:31)
at Function._load (module.js:293:12)
at require (module.js:346:19)
at Object.<anonymous> (/Users/ricky/node_modules/db-oracle/db-oracle.js:12:15)
at Module._compile (module.js:406:26)
at Object..js (module.js:445:10)
at Module.load (module.js:334:31)
at Function._load (module.js:293:12)
at require (module.js:346:19)
```

For Mac OS X I have to use the version 10.2 of the instant client and sdk.
I make the links of the libnnz10.dylib to the libnnz11.dylib so it compiles without problems.

Anyone has any glue?

**Comment by josecardozo** [comment]
Ok, so I try to substitute my OCI library to the x86_64, and again everything goes fine during the installation, but when I run the app goes like this:

```
gdb --args node server_js.js
(...)
(gdb) run
Starting program: /Users/ricky/local/node-v0.4.8/bin/node server_js.js
(...)
... done

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x0000000000000000
0x0000000126cd949e in lpmapd ()
(gdb) bt
#0  0x0000000126cd949e in lpmapd ()
#1  0x0000000126ca3f6c in lfvLoadPkg ()
#2  0x0000000126ca3ba5 in lfvSetShlMode ()
#3  0x0000000126ca31a3 in lfvini1 ()
#4  0x0000000126ca2e72 in lfvinit ()
#5  0x0000000126700491 in kpummpin ()
#6  0x00000001259e51b3 in kpuenvcr ()
#7  0x0000000125ae1116 in OCIEnvCreate ()
#8  0x00000001258066b6 in oracle::occi::Environment::createEnvironment ()
#9  0x0000000100eada87 in node_db_oracle::Connection::Connection (this=0x100816d40) at connection.cc:9
#10 0x0000000100eb0587 in node_db_oracle::Oracle::Oracle (this=0x100816d10) at oracle.cc:7
#11 0x0000000100eaf97e in node_db_oracle::Oracle::New (args=@0x7fff5fbfeb60) at oracle.cc:34
#12 0x000000010007db8e in v8::internal::Builtin_HandleApiCallConstruct ()
Previous frame inner to this frame (gdb could not unwind past this frame)
```

Looks weird. Maybe something with the Oracle Library for Mac OS X.

**Comment by josecardozo** [comment]
Ok, here I got the confirmation. It's a problem with the OCI for OS X Lion.

https://forums.oracle.com/forums/thread.jspa?threadID=2187558&tstart=0

Closing the issue.
